version: '3'
services:
  smashing:
    hostname: smashing
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec smashing start -p 3030 -a '0.0.0.0'"
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 3030:3030
    volumes:
      - ./smashing:/smashing
    networks:
      - frontend
    environment:
      SMASHING_KEY: ${SMASHING_KEY}
      TWITTER_CONSUMER_KEY: ${TWITTER_CONSUMER_KEY}
      TWITTER_CONSUMER_SECRET: ${TWITTER_CONSUMER_SECRET}
      TWITTER_ACCESS_TOKEN: ${TWITTER_ACCESS_TOKEN}
      TWITTER_TOKEN_SECRET: ${TWITTER_TOKEN_SECRET}

networks:
  frontend:
    driver: bridge
